var myString = "Hello World";
var myNum = 2;
var myBool = true;
var myVar = { a: 7 };
var myArray = ['a', 'b', 'c']; // Array of strings only
var numArray = [1, 2, 3]; // Array of numbers only
var boolArray = [true, false, true]; // Array of boolean only
var myStrArray = ['a', 'b', 'c']; // Array of strings only
var myNumArray = [1, 2, 3]; // Array of numbers only
var myBoolArray = [true, false]; // Array of boolean only
var strNumTuple = ['hello', 4]; // Array should match said pattern i.e first should be string and second should be number, rest can be anything.
var myVoid = undefined;
var myNull = null;
var myUndefined = undefined;
console.log("myString => " + myString);
console.log("myNum => " + myNum);
console.log("myBool => " + myBool);
console.log("myVar => " + myVar);
console.log("myArray => " + myArray);
console.log("numArray => " + numArray);
console.log("boolArray => " + boolArray);
console.log("myStrArray => " + myStrArray);
console.log("myNumArray => " + myNumArray);
console.log("myBoolArray => " + myBoolArray);
console.log("strNumTuple => " + strNumTuple);
console.log("myNull => " + myNull);
console.log("myUndefined => " + myUndefined);
